# Use a imagem Python base
FROM python:3.10-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo de dependências
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação (que contém as definições das tarefas)
COPY ./app /app/app

# Comando para iniciar o worker do Celery
# app.tasks:celery_app -> "arquivo" tasks.py, "variável" celery_app
CMD ["celery", "-A", "app.tasks:celery_app", "worker", "--loglevel=info"]